import type { Archetype, ClassStatArray, RacialBonus } from './types';

export const ARCHETYPES: Archetype[] = [
  {
    id: 'human-warrior',
    name: 'Humano Guerrero',
    emoji: '⚔️',
    primaryColor: '#d4af37',
    secondaryColor: '#8b4513',
    description: 'Versátil y determinado. El combatiente clásico.',
    classSuggestion: 'Guerrero',
    raceSuggestion: 'Humano',
  },
  {
    id: 'elf-mage',
    name: 'Elfo Mago',
    emoji: '✨',
    primaryColor: '#4169e1',
    secondaryColor: '#90ee90',
    description: 'Arcano y elegante. El lanzador de hechizos.',
    classSuggestion: 'Mago',
    raceSuggestion: 'Elfo',
  },
  {
    id: 'dwarf-cleric',
    name: 'Enano Clérigo',
    emoji: '⛪',
    primaryColor: '#dc143c',
    secondaryColor: '#ffd700',
    description: 'Sagrado y resistente. El sanador del grupo.',
    classSuggestion: 'Clérigo',
    raceSuggestion: 'Enano',
  },
  {
    id: 'halfling-rogue',
    name: 'Halfling Pícaro',
    emoji: '🗡️',
    primaryColor: '#696969',
    secondaryColor: '#c0c0c0',
    description: 'Ágil y astuto. El maestro del sigilo.',
    classSuggestion: 'Pícaro',
    raceSuggestion: 'Halfling',
  },
  {
    id: 'tiefling-warlock',
    name: 'Tiefling Brujo',
    emoji: '👹',
    primaryColor: '#8b008b',
    secondaryColor: '#ff69b4',
    description: 'Oscuro y pactante. El infernal.',
    classSuggestion: 'Brujo',
    raceSuggestion: 'Tiefling',
  },
  {
    id: 'orc-barbarian',
    name: 'Orco Bárbaro',
    emoji: '💪',
    primaryColor: '#228b22',
    secondaryColor: '#ff4500',
    description: 'Feroz y salvaje. La furia hecha carne.',
    classSuggestion: 'Bárbaro',
    raceSuggestion: 'Orco',
  },
  {
    id: 'dragonborn-paladin',
    name: 'Dracónido Paladín',
    emoji: '🐉',
    primaryColor: '#ffa500',
    secondaryColor: '#000000',
    description: 'Leal y noble. El campeón de la justicia.',
    classSuggestion: 'Paladín',
    raceSuggestion: 'Dracónido',
  },
  {
    id: 'gnome-artificer',
    name: 'Gnomo Artificiero',
    emoji: '⚙️',
    primaryColor: '#ff69b4',
    secondaryColor: '#87ceeb',
    description: 'Ingenioso e inventivo. El mago de los aparatos.',
    classSuggestion: 'Artificiero',
    raceSuggestion: 'Gnomo',
  },
  {
    id: 'halfelf-bard',
    name: 'Semiélfico Bardo',
    emoji: '🎭',
    primaryColor: '#daa520',
    secondaryColor: '#f0e68c',
    description: 'Carismático y versátil. El artista de la magia.',
    classSuggestion: 'Bardo',
    raceSuggestion: 'Semiélfico',
  },
  {
    id: 'human-ranger',
    name: 'Humano Explorador',
    emoji: '🏹',
    primaryColor: '#8b7355',
    secondaryColor: '#228b22',
    description: 'Independiente y preciso. El cazador solitario.',
    classSuggestion: 'Explorador',
    raceSuggestion: 'Humano',
  },
  {
    id: 'elf-monk',
    name: 'Elfo Monje',
    emoji: '🥋',
    primaryColor: '#ffffff',
    secondaryColor: '#000000',
    description: 'Disciplinado e iluminado. El guerrero sin armas.',
    classSuggestion: 'Monje',
    raceSuggestion: 'Elfo',
  },
  {
    id: 'dragonborn-sorcerer',
    name: 'Dracónido Hechicero',
    emoji: '🔥',
    primaryColor: '#ff4500',
    secondaryColor: '#ffd700',
    description: 'Mágico por naturaleza. El portador de magia innata.',
    classSuggestion: 'Hechicero',
    raceSuggestion: 'Dracónido',
  },
];

export const CLASS_STAT_ARRAYS: ClassStatArray[] = [
  { class: 'Guerrero', str: 15, dex: 14, con: 14, int: 10, wis: 12, cha: 10 },
  { class: 'Mago', str: 8, dex: 14, con: 13, int: 16, wis: 12, cha: 10 },
  { class: 'Clérigo', str: 12, dex: 10, con: 14, int: 13, wis: 16, cha: 13 },
  { class: 'Pícaro', str: 8, dex: 16, con: 12, int: 14, wis: 11, cha: 13 },
  { class: 'Brujo', str: 10, dex: 12, con: 13, int: 12, wis: 12, cha: 15 },
  { class: 'Bárbaro', str: 16, dex: 13, con: 15, int: 8, wis: 11, cha: 10 },
  { class: 'Paladín', str: 15, dex: 10, con: 13, int: 10, wis: 11, cha: 15 },
  { class: 'Artificiero', str: 10, dex: 12, con: 14, int: 15, wis: 12, cha: 11 },
  { class: 'Bardo', str: 10, dex: 12, con: 12, int: 12, wis: 12, cha: 15 },
  { class: 'Explorador', str: 13, dex: 15, con: 13, int: 12, wis: 14, cha: 10 },
  { class: 'Monje', str: 12, dex: 16, con: 12, int: 12, wis: 14, cha: 10 },
  { class: 'Hechicero', str: 10, dex: 12, con: 14, int: 12, wis: 12, cha: 15 },
];

export const RACIAL_BONUSES: RacialBonus[] = [
  { race: 'Humano', str: 1, dex: 1, con: 1, int: 1, wis: 1, cha: 1, description: '+1 a todos' },
  { race: 'Elfo', dex: 2, int: 2, description: '+2 DES, +2 INT' },
  { race: 'Enano', con: 2, wis: 2, description: '+2 CON, +2 SAB' },
  { race: 'Halfling', dex: 2, cha: 1, description: '+2 DES, +1 CAR' },
  { race: 'Tiefling', int: 2, cha: 2, description: '+2 INT, +2 CAR' },
  { race: 'Orco', str: 2, con: 1, description: '+2 FUE, +1 CON' },
  { race: 'Dracónido', str: 2, cha: 2, description: '+2 FUE, +2 CAR' },
  { race: 'Gnomo', int: 2, description: '+2 INT' },
  { race: 'Semiélfico', dex: 2, cha: 1, description: '+2 DES, +1 CAR' },
];

export const SKILLS_5E = [
  'Acrobacias','Atletismo','C. Arcano','Engaño','Historia','Interpretación',
  'Intimidación','Investigación','Juego de Manos','Medicina','Naturaleza',
  'Percepción','Perspicacia','Persuasión','Religión','Sigilo','Supervivencia',
  'Trato con Animales',
];

export const CONDITIONS_5E = [
  'Agarrado','Apresado','Aturdido','Cegado','Derribado','Encantado',
  'Ensordecido','Envenenado','Asustado','Incapacitado','Invisible',
  'Paralizado','Petrificado','Inconsciente',
];
